sudo: required
dist: trusty

language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DALICE_TEST=ON -DALICE_EXAMPLES=ON ..
  - make run_tests
  - ./test/run_tests
  - make tutorial1 tutorial2 tutorial3 tutorial4

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
  