sudo: required
dist: trusty

language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DALICE_TEST=ON -DALICE_EXAMPLES=ON ..
  - make run_tests
  - ./test/run_tests
  - make tutorial1 tutorial2 tutorial3 tutorial4
  - make

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0

before_install:
  - eval "${MATRIX_EVAL}"
  